name: security-trivy-scan-repo

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to scan (owner/repo name only)'
        required: true
        default: 'security-cicd'
      ref:
        description: 'Branch or tag to scan'
        required: true
        type: choice
        options:
          - main
          - master
        default: 'main'

permissions:
  actions: read
  contents: read
  security-events: write

env:
  TRIVY_SEVERITY: "HIGH,CRITICAL"
  TRIVY_IGNORE_UNFIXED: "false"
  DT_PROTO: http
  DT_HOST: ${{ secrets.DTRACK_HOSTNAME }}
  DT_PORT: ${{ secrets.DTRACK_PORT }}
  DT_API_KEY: ${{ secrets.DTRACK_API_KEY }}

concurrency:
  group: security-${{ github.event.inputs.repository }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  trivy_gate:
    name: Trivy Gate (fail-fast)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: 'Vietnam-Silicon/${{ github.event.inputs.repository }}'
          token: ${{ secrets.GHA_CICD_TOKEN }}
          ref: '${{ github.event.inputs.ref }}'
          persist-credentials: false

      - name: Generate SARIF (FS)
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          scan-type: 'fs'          
          scan-ref: '.'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'  
          vuln-type: 'library'
          severity: ${{ env.TRIVY_SEVERITY }}
          ignore-unfixed: ${{ env.TRIVY_IGNORE_UNFIXED }}
          exit-code: '0'
          hide-progress: 'true'

          

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Trivy FS scan (fail on HIGH/CRITICAL)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: ${{ env.TRIVY_SEVERITY }}
          ignore-unfixed: ${{ env.TRIVY_IGNORE_UNFIXED }}
          exit-code: '1'
          hide-progress: 'true'

  trivy_report:
    name: Trivy Report (Create SBOM And Upload Dependency-Track)
    runs-on: prod-runner-set  
    needs: trivy_gate
    if: always()
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: 'Vietnam-Silicon/${{ github.event.inputs.repository }}'
          token: ${{ secrets.GHA_CICD_TOKEN }}
          ref: '${{ github.event.inputs.ref }}'

      - name: Generate CycloneDX SBOM
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'cyclonedx'
          output: 'sbom.json'

      - name: Resolve next projectVersion (v1, v2, v3, ...)
        id: ver
        shell: bash
        env:
          PROJECT_NAME: ${{ github.event.inputs.repository }}
        run: |
          set -euo pipefail
          BASE="${DT_PROTO}://${DT_HOST}:${DT_PORT}"

          # URL-encode project name an toàn
          NAME_ENC=$(jq -rn --arg x "$PROJECT_NAME" '$x|@uri')

          echo "🔍 Finding next version for project: $PROJECT_NAME"
          # Tăng dần từ v1 đến khi gặp version chưa tồn tại
          n=1
          max=1000  # guard tránh vòng lặp vô hạn nếu có sự cố
          while (( n <= max )); do
            ver="v${n}"
            code=$(curl -s -o /dev/null -w "%{http_code}" \
              -H "X-Api-Key: ${DT_API_KEY}" \
              "${BASE}/api/v1/project/lookup?name=${NAME_ENC}&version=${ver}" || true)
            if [[ "$code" == "200" ]]; then
              # version đã tồn tại -> thử tiếp
              ((n++))
            else
              # gặp version chưa tồn tại -> dùng nó
              echo "✅ Using new version: ${ver}"
              echo "version=${ver}" >> "$GITHUB_OUTPUT"
              break
            fi
          done            

      - name: Upload SBOM to Dependency-Track
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          protocol: 'https'
          serverHostname: ${{ secrets.DTRACK_HOSTNAME }}
          port: ${{ secrets.DTRACK_PORT }}
          apiKey: ${{ secrets.DTRACK_API_KEY }}
          projectName: '${{ github.event.inputs.repository }}'
          projectVersion: ${{ steps.ver.outputs.version }}
          bomFilename: '${{ github.workspace }}/sbom.json'
          autoCreate: true
