name: Security · Trivy

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: "0 3 * * *"

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t trivy-demo .

      - name: Scan source code (SCA)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy-fs.sarif
          scanners: vuln,misconfig,secret,license
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 1

      - name: Upload SARIF (fs)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          image-ref: trivy-demo
          format: sarif
          output: trivy-image.sarif
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 1

      - name: Upload SARIF (image)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif
